name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@30008f1458a5a2c97054bfe118fe33d75976c482
        run: npx cypress run
        with: 
          start: npm start
      

